name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${REGISTRY}/${{ github.repository_owner }}/s3cmd"
  
jobs:
  build-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Login to Registry
        id: docker-login
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Buildx
        id: docker-build
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag $IMAGE_NAME:latest \
            --output "type=image,push=true" \
            --file Dockerfile .
